#!/bin/env sh

# edit the waybar config file
#
# break .config/waybar/config.jsonc into lines
# search for line that reads '"persistent_workspaces": {'
#
# if the next line says "eDP-1" then swap that
# (and following two lines) to "DP-4", or swap back
#
# "1": ["eDP-1"],   //   "1": ["DP-4"],
# "2": ["eDP-1"],   //   "2": ["DP-4"],
# "3": ["eDP-1"],   //   "3": ["DP-4"],

if grep -q '"1": \["eDP-1"\]' ~/.config/waybar/config.jsonc; then
     sed -i 's/\"1\": \[\"eDP-1\"\]/\"1\": \[\"DP-4\"\]/g' ~/.config/waybar/config.jsonc
     sed -i 's/\"2\": \[\"eDP-1\"\]/\"2\": \[\"DP-4\"\]/g' ~/.config/waybar/config.jsonc
     sed -i 's/\"3\": \[\"eDP-1\"\]/\"3\": \[\"DP-4\"\]/g' ~/.config/waybar/config.jsonc
else
     sed -i 's/\"1\": \[\"DP-4\"\]/\"1\": \[\"eDP-1\"\]/g' ~/.config/waybar/config.jsonc
     sed -i 's/\"2\": \[\"DP-4\"\]/\"2\": \[\"eDP-1\"\]/g' ~/.config/waybar/config.jsonc
     sed -i 's/\"3\": \[\"DP-4\"\]/\"3\": \[\"eDP-1\"\]/g' ~/.config/waybar/config.jsonc
fi

# kill and reload waybar
killall waybar

# start waybar
waybar
